### ISSUE TITLE
Want __attribute__ ((aligned_seal))

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/clang#101]
I'd like to be able to declare types with an alignment (and by extension size) suitable for sealing.  For example, this lets you declare a struct to be page sized (which happens to also yield page alignment in sensible mallocs).

``` C
struct
#if _MIPS_SZCAP == 128
__attribute__ ((aligned(4096)))
#endif
cheri_fd {
        CHERI_SYSTEM_OBJECT_FIELDS;
        int     cf_fd;  /* Underlying file descriptor. */
 };
```

It would be better to have a magic keyword to avoid the ifdefs and avoid the need to port such code to new ISAs.  Something like `__attribute__ ((aligned_seal))` would be great.  I think this would be most useful on types, but it might make sense for global and stack allocations.

**Comment by arichardson** [comment]
We no longer use a different representation for sealed caps.
