### ISSUE TITLE
Need -Wold-style-declerations

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/clang#103]
@rwatson has reported that functions declared without arguments result in unusable functions.  We should implement the equivalent of gcc's `-Wold-style-declerations` and make it an error in pure-capability mode.

There's an llvm that has seen no action we'll probably need to do it https://llvm.org/bugs/show_bug.cgi?id=10486

**Comment by rwatson** [comment]
The example I encountered was a header file in ```less(1)```, in which all function prototypes are K&R, and none work in CheriABI.

**Comment by arichardson** [comment]
We have -Wmips-cheri-prototypes for this now.
