### ISSUE TITLE
-O2 does not pass parameters correctly to a called function in CheriABI.

### ISSUE THREAD

**Issue by Jerryxia32** [CTSRD-CHERI/clang#105]
When compiling the FFT benchmark in MiBench, -O2 compiles but does not pass the parameters correctly:

```
    MAXSIZE = 4096;
    ...
    fft_float (MAXSIZE,invfft,RealIn,ImagIn,RealOut,ImagOut);
```

for debugging, the first line inside `void fft_float(unsigned  NumSamples, int InverseTransform, float    *RealIn, float    *ImagIn, float    *RealOut, float    *ImagOut )` is:

```
    printf("Enters fft_float, NumSamples = %u.\n", NumSamples);
```

On -O2, the binary outputs:
`Enters fft_float, NumSamples = 1. Error in fft():  NumSamples=1 is not power of two`

However on -O0:
`Enters fft_float, NumSamples = 4096.`
and the program terminates successfully.

Compiled with

```
make CC='/home/hx242/ctsrd/cheriscripts/src/output/sdk128/bin/clang -static -msoft-float -O2 -g 
-integrated-as --sysroot=/home/hx242/ctsrd/cheriscripts/src/output/sdk128/sysroot 
-B=/home/hx242/ctsrd/cheriscripts/src/output/sdk128/bin -target cheri-unknown-freebsd 
-mabi=sandbox -mllvm -cheri128 -cheri-linker -Wl,--whole-archive -lstatcounters -Wl,--no-whole-archive' 
LD='/home/hx242/ctsrd/cheriscripts/src/output/sdk128/bin/clang -cheri-linker -static 
--sysroot=/home/hx242/ctsrd/cheriscripts/src/output/sdk128/sysroot -Wl,--whole-archive 
-lstatcounters -Wl,--no-whole-archive' 
STRIP='/home/hx242/ctsrd/cheriscripts/src/output/sdk128/bin/strip' CPP='/home/hx242/ctsrd/cheriscripts/src/output/sdk128/bin/clang -E' 
CPPFLAGS='--sysroot=/home/hx242/ctsrd/cheriscripts/src/output/sdk128/sysroot'
```

Invoked with `./fft 4 4096`

Reproducible on CHERI-128 FPGA running under CheriBSD-128.
[FFT.zip](https://github.com/CTSRD-CHERI/clang/files/558386/FFT.zip)

**Comment by davidchisnall** [comment]
Please will you produce a reduced test case (i.e. small stand-alone C file that you can put in a gist)?

**Comment by davidchisnall** [comment]
Also, if this is a bug at -O2, it's an LLVM bug not a clang bug.  Please file a bug report with a useful test case against LLVM.
