### ISSUE TITLE
Failing to build jsrun with no global bounds

### ISSUE THREAD

**Issue by gameboo** [CTSRD-CHERI/clang#109]
Here is the command output :

make clean && CHERI_SDK=~/sdks/jenkins/cheri256-sdk/ make VERSION=cheri256
rm -f jsrun ffigen duktape.o jsrun.o modules.o worker.o env.o
/home/aj443/sdks/jenkins/cheri256-sdk//bin/cheri-unknown-freebsd-clang -O2 -pipe   -DDUK_OPT_NO_ASSERTIONS=1 -DDUK_OPT_UNDERSCORE_SETJMP=1 -DDUK_OPT_DEBUG=3 -msoft-float -mabi=sandbox -mllvm -cheri-no-global-bounds -DDUK_OPT_FORCE_ALIGN=32 -DDUK_USE_PACKED_TVAL=1 --sysroot=/home/aj443/sdks/jenkins/cheri256-sdk//sysroot -I/usr/include/edit -v -c duktape.c -o duktape.o
clang version 3.8.0 (git://github.com/CTSRD-CHERI/clang.git 36ee6ec8fe5213ea5d609e299164e2ff32f6a93a) (git://github.com/CTSRD-CHERI/llvm.git 28220ddaea1a5848388b1072bc1200a166f53557)
Target: cheri-unknown-freebsd
Thread model: posix
InstalledDir: /home/aj443/sdks/jenkins/cheri256-sdk//bin
 "/home/aj443/sdks/jenkins/cheri256-sdk/bin/clang-3.8" -cc1 -triple cheri-unknown-freebsd -emit-obj -disable-free -disable-llvm-verifier -main-file-name duktape.c -mrelocation-model static -mthread-model posix -mdisable-fp-elim -masm-verbose -mconstructor-aliases -target-feature +soft-float -target-abi sandbox -msoft-float -mfloat-abi soft -v -dwarf-column-info -coverage-file /home/aj443/devstuff/jsrun/duktape.o -resource-dir /home/aj443/sdks/jenkins/cheri256-sdk/bin/../lib/clang/3.8.0 -D DUK_OPT_NO_ASSERTIONS=1 -D DUK_OPT_UNDERSCORE_SETJMP=1 -D DUK_OPT_DEBUG=3 -D DUK_OPT_FORCE_ALIGN=32 -D DUK_USE_PACKED_TVAL=1 -I /usr/include/edit -isysroot /home/aj443/sdks/jenkins/cheri256-sdk//sysroot -O2 -fdebug-compilation-dir /home/aj443/devstuff/jsrun -ferror-limit 19 -fmessage-length 225 -fobjc-runtime=gnustep -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -cheri-linker -mllvm -cheri-no-global-bounds -o duktape.o -x c duktape.c
clang -cc1 version 3.8.0 based upon LLVM 3.8.0svn default target cheri-unknown-freebsd
#include "..." search starts here:
#include <...> search starts here:
 /usr/include/edit
 /home/aj443/sdks/jenkins/cheri256-sdk/bin/../lib/clang/3.8.0/include
 /home/aj443/sdks/jenkins/cheri256-sdk//sysroot/usr/include
End of search list.
clang-3.8: error: unable to execute command: Segmentation fault (core dumped)
clang-3.8: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.8.0 (git://github.com/CTSRD-CHERI/clang.git 36ee6ec8fe5213ea5d609e299164e2ff32f6a93a) (git://github.com/CTSRD-CHERI/llvm.git 28220ddaea1a5848388b1072bc1200a166f53557)
Target: cheri-unknown-freebsd
Thread model: posix
InstalledDir: /home/aj443/sdks/jenkins/cheri256-sdk//bin
clang-3.8: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-3.8: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-3.8: note: diagnostic msg: /tmp/duktape-a85d70.c
clang-3.8: note: diagnostic msg: /tmp/duktape-a85d70.sh
clang-3.8: note: diagnostic msg: 

********************
*** Error code 254

Here are the files:

https://gist.github.com/gameboo/65e557d097a8d682413d65d4dd0da465

**Comment by gameboo** [comment]
other failure case here:

https://gist.github.com/gameboo/d4ee49a93c0b925a9651b5b15d146e3f

**Comment by Jerryxia32** [comment]
After the patch, segfault still occurred for this benchmark.
```
 "/home/hx242/ctsrd/cheriscripts/src/output/sdk128/bin/clang-3.8" "-cc1" "-triple" "cheri-unknown-freebsd" "-emit-obj" "-disable-free" "-disable-llvm-verifier" "-main-file-name" "audio.c" "-static-define" "-mrelocation-model" "static" "-mthread-model" "posix" "-mdisable-fp-elim" "-masm-verbose" "-mconstructor-aliases" "-target-feature" "+soft-float" "-target-abi" "sandbox" "-msoft-float" "-mfloat-abi" "soft" "-dwarf-column-info" "-D" "HAVE_CONFIG_H" "-D" "LOCALEDIR=\"/usr/local/share/locale\"" "-O2" "-Wall" "-ferror-limit" "19" "-fmessage-length" "84" "-fobjc-runtime=gnustep" "-fdiagnostics-show-option" "-fcolor-diagnostics" "-vectorize-loops" "-vectorize-slp" "-cheri-linker" "-mllvm" "-cheri128" "-mllvm" "-cheri-no-global-bounds" "-x" "c" "audio-26be05.c"
```
[gist](https://gist.github.com/Jerryxia32/023d0e4e8c9145f9fe9a0ce15ace4836)

**Comment by Jerryxia32** [comment]
After the patch, one benchmark still fails
```
/home/hx242/ctsrd/cheriscripts/src/output/sdk256/bin/clang -static -msoft-float -O2 -integrated-as --sysroot=/home/hx242/ctsrd/cheriscripts/src/output/sdk256/sysroot -B=/home/hx242/ctsrd/cheriscripts/src/output/sdk256/bin -target cheri-unknown-freebsd -mabi=sandbox -mllvm -cheri-no-global-bounds -cheri-linker -Wl,--whole-archive -lstatcounters -Wl,--no-whole-archive -all-static -DHAVE_CONFIG_H -I. -I. -I. -Ilibmad -I./libid3tag -Iintl  			-DLOCALEDIR=\"/usr/local/share/locale\"  --sysroot=/home/hx242/ctsrd/cheriscripts/src/output/sdk256/sysroot  -Wall -O2 -c audio.c
```
https://gist.github.com/Jerryxia32/f34dd62cba980d09605b4a9b67cd8e68

**Comment by davidchisnall** [comment]
This is not a preprocessed C file, so I can't reproduce it.

**Comment by davidchisnall** [comment]
This one doesn't even get to codegen: it fails with a huge number of compiler errors.
