### ISSUE TITLE
Feature request: When compiling for the pure-capability ABI, generate errors rather than warnings for wrong prototypes

### ISSUE THREAD

**Issue by rwatson** [CTSRD-CHERI/clang#112]
Feature request: In the pure-capability ABI, a lack of function-prototype arguments leads to using the variadic calling convention -- which is almost never the desired calling convention. It would probably be best if Clang generated an error rather than a warning when trying to compile code without adequate function prototypes, as the resulting code will almost never actually work -- and it would be better to debug compile-time failures than run-time failures for this.

(Tagging @brooksdavis as he had also observed that this would be a good idea.)

**Comment by davidchisnall** [comment]
This can be done in the build system by specifying `-Werror=implicit-function-declaration`.

**Comment by brooksdavis** [comment]
The problem isn't actually missing prototypes, it's wrong prototypes.  In less, there's a `funcs.h` which contains invalid prototypes like:
```C
        public char * save ();
        public VOID_POINTER ecalloc ();
        public char * skipsp ();
        public int sprefix ();
        public void quit ();
        public void raw_mode ();
...
```
I suspect there's a warning for these non-void argument lists, but I've been unable to figure out what it is.

**Comment by brooksdavis** [comment]
For added fun, the actual functions have K&R definitions....

**Comment by kgudka** [comment]
This feature has now been added in 8c3c47f18a215953bc7eae4f5813f3d83fbf61d7 in the form of the warning `-Wmips-cheri-prototypes`. It is enabled by default when `-mabi=purecap`. To make it an error, pass `-Werror=mips-cheri-prototypes`.

Here is sample output:

```
/cheribsd/contrib/tcp_wrappers/hosts_access.c:138:9: error: call to function 'table_match' with no prototype may lead to runtime stack corruption on CHERI [-Werror,-Wmips-cheri-prototypes]
    if (table_match(hosts_allow_table, request))
        ^~~~~~~~~~~
/cheribsd/contrib/tcp_wrappers/hosts_access.c:90:12: note: candidate function declaration needs parameter types
static int table_match();
```
