### ISSUE TITLE
Need a way to annotate pointers as non-alignment preserving

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/clang#115]
In FreeBSD, people use the BDB interface without a backing file as a hash table.  It stores key/value pairs which are passed in as DBT arguments:
```C
/* Key/data structure -- a Data-Base Thang. */
typedef struct {
        void    *data;                  /* data */
        size_t   size;                  /* data length */
} DBT;
```
Due to details of both the `DB_HASH` and `DB_RBTREE` implementations, data is stored at no better than 2-byte alignment.  I'd like a way to indicate that the `data` pointer is not alignment preserving and that it's an error for data to point to something containing pointers (typically it points to a pointer).

**Comment by davidchisnall** [comment]
I believe that using `char*` instead of `void*` here will give a warning that the cast increases alignment.

**Comment by brooksdavis** [comment]
It would, but this isn't an API we can change as it's part of libc.

**Comment by davidchisnall** [comment]
What happens if you stick `__attribute__((aligned(2)))` on the struct?  That lets Clang / LLVM know that the expected alignment is 2.  We can then add a warning that the pointer is under-aligned.

**Comment by davidchisnall** [comment]
It appears that we don't warn with the attribute, and it's not quite as easy as I thought to figure out where the warning should go...

**Comment by davidchisnall** [comment]
It appears that I misunderstood the bug report.  I've added a warning so that if DBT is under-aligned, then you can find it, but warning that a pointer points to something under-aligned is not easy to express within the C type system.  You want something like a `void*`, but with a restriction that it doesn't allow casts from it to something with alignment greater than 2.  You effectively want to write something like this:


```c
__attribute__((aligned(2)))
typedef void void2;
void2 *data;
...
void **p = data; // <- Warn here.
```

**Comment by davidchisnall** [comment]
By the way, the above example compiles, but by the time we do the type check on the implicit cast, clang has canonicalised the types and so it's treated as a `void*` to other pointer cast.
