### ISSUE TITLE
Crash compiling cheritest_helper

### ISSUE THREAD

**Issue by arichardson** [CTSRD-CHERI/clang#117]
Source and driver script: https://gist.github.com/RichardsonAlex/49b97988a495afaffcdb73f5f6f8ca23

**Comment by RichardsonAlex** [comment]
Debug build of clang gives the following error: `Assertion failed: (isExpr() && "This is not an expression"), function getExpr, file ../../include/llvm/MC/MCInst.h, line 94.`

**Comment by RichardsonAlex** [comment]
Goes away if I comment out the inline assembly here:

```
	case CHERITEST_HELPER_VM_FAULT_XFAULT:
		// It's no longer easy to trigger a TLB execute fault from C code,
		// because all function pointers are derived from PCC and so will
		// either be executable or generate capability faults that have a
		// higher precedence than the TLB faults.  We could map a
		// non-executable page into PCC for this test, but it's easier to just
		// do a MIPS jump.
		__asm__ volatile ("jal 4" : : :"memory");
		break;
	}
```

**Comment by brooksdavis** [comment]
As I commented to @kgudka before, I suspect this somewhat nonsensical code assembles to `li $t9, 4; jal $t9` so expanding it as such probably makes sense.

**Comment by davidchisnall** [comment]
This looks to be an upstream bug, and the fix is nontrivial.  It doesn't handle the case where the argument is an immediate at all.

**Comment by kgudka** [comment]
The suggested temporary fix from @brooksdavis is what I had applied to cheritest-helper.c to get it to compile and is what is in the cheribsd master branch. However, if this is an upstream bug then we should probably file a bug report.

**Comment by brooksdavis** [comment]
It certainly shouldn't crash.  Once could argue that it's nonsense you shouldn't write, but it's consistant with many other assembly pseudos.
