### ISSUE TITLE
Pointers to members are incorrect in CHERI

### ISSUE THREAD

**Issue by RichardsonAlex** [CTSRD-CHERI/clang#121]
I have added a test case to my fork but I am not sure what the correct codegen for pointers to members is

**Comment by davidchisnall** [comment]
The [relevant part of the Itanium ABI](https://mentorembedded.github.io/cxx-abi/abi.html#member-pointers).  The second element in the pointer is an offset, so probably want to remain a `i64`.  The first element is either a pointer to the function (low bit 0) or 1 + the offset in the vtable as a `ptrdiff_t` (low bit 1).  For CHERI, we should represent the first one as a capability and use the tag bit to differentiate between a pointer and a vtable offset.

For a v2 ABI, we should consider protecting the integrity of this pair.

**Comment by RichardsonAlex** [comment]
Seems like that link no longer works, this one does: https://itanium-cxx-abi.github.io/cxx-abi/abi.html#member-pointers

**Comment by RichardsonAlex** [comment]
According to the clang source code the MIPS target is using the ARM member pointer layout (section 3.2.1 of http://infocenter.arm.com/help/topic/com.arm.doc.ihi0041e/IHI0041E_cppabi.pdf)
I'm not sure whether that makes sense for CHERI as we can use the tag bit to differentiate between nonvirtual and virtual.
