### ISSUE TITLE
Assertion failed: (!NodePtr->isKnownSentinel()), function operator*

### ISSUE THREAD

**Issue by bsdjhb** [CTSRD-CHERI/clang#122]
Compiling a little threaded test application I use with the sandbox ABI triggers an assertion failure:

> /usr/cheri/bin/clang --sysroot=/usr/obj/mips.mips64/usr/home/john/work/cheri/git/cheribsd/tmp -B /usr/obj/mips.mips64/usr/home/john/work/cheri/git/cheribsd/tmp/usr/bin -B /usr/obj/mips.mips64/usr/home/john/work/cheri/git/cheribsd/tmp/legacy/usr/bin -msoft-float -mabi=sandbox -cheri-linker -O2 -pipe   -g -MD  -MF.depend.thread.o -MTthread.o -std=gnu99 -fstack-protector-strong -Wsystem-headers -Wall -Wno-format-y2k -Wno-uninitialized -Wno-pointer-sign -Wno-empty-body -Wno-string-plus-int -Wno-unused-const-variable -Wno-tautological-compare -Wno-unused-value -Wno-parentheses-equality -Wno-unused-function -Wno-enum-conversion -Wno-unused-local-typedef -Wno-switch -Wno-switch-enum -Wno-knr-promoted-parameter  -Qunused-arguments  -c thread.c -o thread.o
Assertion failed: (!NodePtr->isKnownSentinel()), function operator*, file /home/john/work/cheri/git/llvm/include/llvm/ADT/ilist_iterator.h, line 126.
clang-5.0: error: unable to execute command: Abort trap (core dumped)
clang-5.0: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 5.0.0 (git@github.com:CTSRD-CHERI/clang.git 0d35e16aa96019fd68d8a5968de9676ce6b6fcad) (git@github.com:CTSRD-CHERI/llvm.git cbb24659c8e125d7e4936fc4fea71b29da62e7ad)
Target: cheri-unknown-freebsd
Thread model: posix
InstalledDir: /usr/cheri/bin

Somewhat reduced test case:
```
#include <err.h>
#include <pthread.h>
#include <pthread_np.h>
#include <stdio.h>
#include <unistd.h>

static int signalled;
static pthread_mutex_t lock;
static pthread_cond_t cv;

void thread_wait(void);

void
thread_wait(void)
{

	pthread_mutex_lock(&lock);
	while (!signalled)
		pthread_cond_wait(&cv, &lock);
	pthread_mutex_unlock(&lock);
}
```

**Comment by kgudka** [comment]
Further reduced test case:

static int signalled;
void f();

void thread_wait(void) {
  while (!signalled)
    f();
}

**Comment by davidchisnall** [comment]
LLVM (not clang) bug.  Fixed now.
