### ISSUE TITLE
Assertion error when building Olden

### ISSUE THREAD

**Issue by arichardson** [CTSRD-CHERI/clang#135]
Reduced test case:

```
// RUN: %clang_cc1 -triple cheri-unknown-freebsd -emit-obj -disable-free -main-file-name hash.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -mconstructor-aliases -target-cpu cheri -target-feature +soft-float -target-abi n64 -msoft-float -mfloat-abi soft -O2 -vectorize-loops -vectorize-slp -cheri-linker -x c %s -o - | FileCheck %s

// XFAIL: *

typedef struct a { struct a * __capability b; } * c;
void d(void) {
  c __capability *e;
  e = &(*e)->b;
}
```

**Comment by davidchisnall** [comment]
The `typedef` makes this difficult to understand, but the same crash happens without it:

```C
struct a { struct a * __capability b; };
void d(void) {
  struct a * __capability *e;
  e = &(*e)->b;
}
```

**Comment by davidchisnall** [comment]
In this version, the LLVM type of `e` is `%struct.a addrspace(200)***`, which seems correct (stack address of a pointer to a capability).  The LLVM type of `&(*e)->b` is `%struct.a addrspace(200)* addrspace(200)*`, so it appears that the address-of operator has given the wrong type for the address of the field.

**Comment by davidchisnall** [comment]
This was fixed to error on this kind of input some time ago.
