### ISSUE TITLE
Bitwise or of uintptr_t constants not allowed in constant expression

### ISSUE THREAD

**Issue by arichardson** [CTSRD-CHERI/clang#146]
```
class ... {
    static const uintptr_t thinFlag = 1;
    static const uintptr_t reservedFlag = 2;
    static const uintptr_t flags = thinFlag | reservedFlag;
    static const uintptr_t reservedValue = 4;
}
```
`/local/scratch/alr48/cheri/qt5/qtwebkit/Source/WTF/wtf/TinyPtrSet.h:375:45: error: in-class initializer for static data member is not a constant expression`

As all of these are integer constant expressions we should probably allow it?

**Comment by davidchisnall** [comment]
This used to work (and I thought we had a test for it).  Was it broken by the constant expression changes that @RichardsonAlex  did?

**Comment by RichardsonAlex** [comment]
I think it works in C but not C++ test. I think even for builtin types the bitwise operations go through the overload resolution code and that might cause operations on uintcap_t to be non-constant?

**Comment by davidchisnall** [comment]
Possible.  I'm not sure about the C++ logic there.
