### ISSUE TITLE
Cast from capability pointer to integer uses ctoptr in hybrid mode

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/clang#152]
Consider the simple C file:
```C
#include <sys/types.h>

__uint64_t
return_offset(void * __capability cap)
{

        return (__uint64_t)cap;
}
```

I would expect this to return the cursor and in pure cap mode it does:
```
$ clang -target cheri-unknown-freebsd -mabi=purecap -o - -S -O2 ptrcast.c
...
        daddiu  $sp, $sp, -32
        csd     $fp, $sp, 24($c11)      # 8-byte Folded Spill
        move     $fp, $sp
        cgetbase $1, $c3
        cgetoffset      $2, $c3
        daddu   $2, $1, $2
        move     $sp, $fp
        cld     $fp, $sp, 24($c11)      # 8-byte Folded Reload
        cjr     $c17
        daddiu  $sp, $sp, 32
```

In hybrid mode `ctoptr` is used
```
$ clang -target cheri-unknown-freebsd  -o - -S -O2 ptrcast.c
...
        daddiu  $sp, $sp, -32
        sd      $fp, 24($sp)            # 8-byte Folded Spill
        move     $fp, $sp
        ctoptr $2, $c3, $c0
        move     $sp, $fp
        ld      $fp, 24($sp)            # 8-byte Folded Reload
        jr      $ra
        daddiu  $sp, $sp, 32
```
I could see an argument for subtracting the base of $c0 from the result, but not requiring a tag.

It's causing a in the debugging sysctls (`KERN_PROC_AUXV` in particular) because the tag wasn't being copied in and thus the casts are returning 0.  See CTSRD-CHERI/cheribsd@991994ebe338328e2bc236be46f19dc9425827df for the change this breaks.

cc: @bsdjhb

**Comment by davidchisnall** [comment]
This is the expected behaviour currently.  In hybrid mode, we try to ensure that operations that work on pointers are consistent, so `(int)x` gives you the same value if `x` is a `T*` or a `T*__capability`.  In the purecap mode, we assume that DDC will be tightly constrained and that `ctoptr` will give null in most cases.

It's not clear how we should handle the case of untagged capabilities.  This might be an argument for the mooted CToInt instruction, which would simply give you the virtual address for tagged and untagged capabilities alike.

**Comment by brooksdavis** [comment]
This behavior seems too inconsistent with pure capabilty mode to be practical.  It also appears that it means there's no way to get the value out of an `__intcap_t` that is used as an integer without resorting to builtins.

**Comment by davidchisnall** [comment]
Casting from an `__intcap_t` to an integer will give you the offset in both modes and casting from a pointer to an `__intcap_t` to an integer will give you an `__intcap_t` containing the capability in both modes.  I believe clang will already warn (even when not targeting CHERI) for pointer to `long` casts that don't go via `intptr_t`.

**Comment by bsdjhb** [comment]
Unfortunately what I need is the absolute virtual address from an untagged capability (or I need to preserve the tags when copying in which is the approach I've taken for now as a workaround).

**Comment by michael-roe** [comment]
What's the use case for this? ( I'm guessing its something like the
debugger trying to interpret a capability from the debugged process).
Diferent C idioms might be called for depending on the semantic intent.

**Comment by bsdjhb** [comment]
In this case, the kernel is reading a capability out of a different process' address space to inspect it and extract the virtual address space.  This is used by debuggers to permit examination of the ELF auxiliary vector of a target process.  procstat -x uses this same code in the kernel.  However, the capability is not for the current process, and the kernel needs an absolute virtual address so it can map the appropriate backing page into the kernel to read/write the auxv data.

**Comment by arichardson** [comment]
There is now a warning for this.
