### ISSUE TITLE
In purecap ABI by value structs are passed as series of i64 arguments

### ISSUE THREAD

**Issue by arichardson** [CTSRD-CHERI/clang#153]
In the hybrid ABI it uses memcpy and passes a pointer starting at >= 64 bytes.
See test/CodeGen/cheri-byval-argument.c

Not sure this is a problem, but it generates tons of code instead of calling memcpy.

**Comment by davidchisnall** [comment]
I think that's normal.  The back end will either lower it to a memcpy call or to a sequence of loads and stores, depending on which makes more sense.

**Comment by RichardsonAlex** [comment]
It ends up generated functions with a huge amount of variables and lots of loads and stores if we have an array of e.g. 2048 bytes (see the output generated by https://github.com/CTSRD-CHERI/clang/blob/master/test/CodeGen/cheri-byval-argument.c). I think the threshold between expanding and using memcpy should be the same (or only slightly higher) between n64 and purecap ABI.

**Comment by davidchisnall** [comment]
The threshold is set in the back end.  I agree that we should be generating a memcpy call for these, but the current threshold is 16 stores, so I'm not quite sure how we are getting 64 bytes not becoming a memcpy call.

**Comment by davidchisnall** [comment]
Hmm, it looks as if this is actually a problem with the calling convention.  For MIPS, we're passing the struct indirectly (via a pointer), in the pure-cap ABI we're passing it all in registers (in the IR - most of which then gets lowered to stack arguments).  I think this is part of the change made by @kgudka regarding byval arguments.

**Comment by RichardsonAlex** [comment]
It seems to be using 8 * capability registers size in bits as the threshold.

**Comment by arichardson** [comment]
Should be fixed.
