### ISSUE TITLE
assert: Decl inserted into wrong lexical context

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/clang#158]
Compiling compress.c I get:
```
Assertion failed: (D->getLexicalDeclContext() == this && "Decl inserted into wrong lexical context"), function addHiddenDecl, file ../tools/clang/lib/AST/DeclBase.cpp, line 1370.
```
Attempting to reduce with creduce_crash_testcase.py resulted in an empty file so I've uploaded reproduction bits in https://gist.github.com/brooksdavis/ee68d484c0f0e1126d9e74d405194331 (also on zeno).

**Comment by RichardsonAlex** [comment]
I think this may be the same as #157

**Comment by brooksdavis** [comment]
Possibly.  The breakage seems to have gotten broader (256-bit is failing in this area in jenkins where only 128-bit seemed broken before).

**Comment by RichardsonAlex** [comment]
confirmed as duplication of #157
