### ISSUE TITLE
cheri_method_suffix attribute hits assert when in extern C

### ISSUE THREAD

**Issue by LawrenceEsswood** [CTSRD-CHERI/clang#166]
Try compiling:

extern "C" __attribute__((cheri_method_suffix(""))) a();

With 

clang --target=cheri-unknown-freebsd -mabi=purecap -nostdinc -fno-builtin -ffreestanding ./main.cpp

**Comment by davidchisnall** [comment]
This doesn't appear to have anything to do with the `extern "C"` part, this also hits an assertion failure:

```c++
__attribute__((cheri_method_suffix("")))
void a();
```

**Comment by LawrenceEsswood** [comment]
I guess thats the danger of automatically reducing test cases.
