### ISSUE TITLE
Capability equivalent of .mask needed

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/clang#47]
To support debugging, we'll want a capability equivalent of the .mask pseudo to indicate which registers were saved to the stack frame.

**Comment by davidchisnall** [comment]
Do the normal CFI directives not work?  The capability registers have all been assigned DWARF register numbers in the back end, so I'd expect them to just work.

**Comment by davidchisnall** [comment]
This directive appears to be completely undocumented.  What does it actually do?  Is it just a subset of the `.cfi_*` directives and therefore obsolete?

**Comment by brooksdavis** [comment]
It's quite plausible it's obsolete.  Sorry I didn't include a link before, it was quite hard to find, the this provides some sketchy documentation.  http://techpubs.sgi.com/library/manuals/2000/007-2418-006/pdf/007-2418-006.pdf

**Comment by davidchisnall** [comment]
Looking at the docs, it appears that it is just another way of writing a subset of the `.cfi_*` directives, which should all work with capability registers already.
