### ISSUE TITLE
Assertion failed: (!empty()), function back, file ../include/llvm/ADT/SmallVector.h, line 157.

### ISSUE THREAD

**Issue by munraj** [CTSRD-CHERI/clang#48]
https://gist.github.com/munraj/ac35a2204ca34a3a5356

[mbv22@f2 /usr/home/mbv21/cheribsd7/lib/libz-cheri]$ /home/mbv21/ctsrd/cherilibs/trunk/tools/sdk/bin/clang -c /usr/home/mbv21/cheribsd7/lib/libz-cheri/deflate-preprocessed.c
Assertion failed: (!empty()), function back, file ../include/llvm/ADT/SmallVector.h, line 157.
clang-3.7: error: unable to execute command: Segmentation fault (core dumped)
clang-3.7: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.7.0 (https://github.com/CTSRD-CHERI/clang 1695e56b14e7841e43a04328ff95267ed59f121e) (http://github.com/CTSRD-CHERI/llvm b6f4c645160874167d364d41637e5b5a98e64d7a)
Target: cheri-unknown-freebsd                                              
Thread model: posix                                                        
clang-3.7: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-3.7: note: diagnostic msg:                                           
********************                                                       
                                                                           
PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:                       
Preprocessed source(s) and associated run script(s) are located at:        
clang-3.7: note: diagnostic msg: /tmp/deflate-preprocessed-16b1e3.c        
clang-3.7: note: diagnostic msg: /tmp/deflate-preprocessed-16b1e3.sh       
clang-3.7: note: diagnostic msg:                                           
                                                                           
********************

**Comment by davidchisnall** [comment]
Could be a more useful error message, but this is caused by a pop without a corresponding push.
