### ISSUE TITLE
compiling sqlite3.c takes forever

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/clang#51]
Compiling sqlite3.c in pure-capability mode takes a very long time (killed after over 27 minutes).

The file in the following gist can be compiled with:

```
clang -integrated-as --target=cheri-unknown-freebsd  -msoft-float -mabi=sandbox sqlite3-processed.c -c -o /dev/null
```

https://gist.github.com/brooksdavis/d36d745d60bd68bd501c

**Comment by davidchisnall** [comment]
LLVM bug (Fixed).
