### ISSUE TITLE
typedefs cannot be usefully used with __capability qualifier

### ISSUE THREAD

**Issue by rwatson** [CTSRD-CHERI/clang#69]
I've been trying to rework ```struct cheri_object``` and types in ```libcheri``` to better distinguish code and data pointers from one another -- particularly useful when we want functions to return function pointers, which is difficult to express legibly/cleanly in C without use of typedefs:

```
--- a/sys/mips/include/cheri.h
+++ b/sys/mips/include/cheri.h
@@ -54,13 +54,26 @@ CTASSERT(sizeof(struct chericap) == CHERICAP_SIZE);
 #endif
 
 /*
+ * Pointer types for (abstract) object capabilities.  When constructing
+ * capabilities for globals, the compiler must know whether a pointer is to
+ * code or data in order to decide whether it should be derived from the
+ * program-counter capability or the default data capability.
+ */
+#if !defined(_KERNEL) && __has_feature(capabilities)
+/* NOTYET: typedef void (*cheri_codeptr_t)(void); */
+typedef void *cheri_codeptr_t;
+typedef void *cheri_dataptr_t;
+typedef void *cheri_typeptr_t;
+#endif
+
+/*
  * Canonical C-language representation of a CHERI object capability -- code
  * and data capabilities in registers or memory.
  */
 struct cheri_object {
 #if !defined(_KERNEL) && __has_feature(capabilities)
-       __capability void       *co_codecap;
-       __capability void       *co_datacap;
+       __capability cheri_codeptr_t    co_codecap;
+       __capability cheri_dataptr_t    co_datacap;
 #else
        struct chericap          co_codecap;
        struct chericap          co_datacap;
```

Unfortunately, this leads to a number of compilation problems as it appears the address-space mechanism may not be seeing much use with typedefs. For example:

```
/home/rnw24/sdk/sdk/bin/cheri-unknown-freebsd-clang -integrated-as --target=cher
i-unknown-freebsd  -msoft-float --sysroot=/home/rnw24/obj/mips.mips64/home/rnw24
/git/cheribsd/tmp  -O -pipe -G0   -I/home/rnw24/git/cheribsd/lib/libc/include -I
/home/rnw24/git/cheribsd/lib/libc/../../include -I/home/rnw24/git/cheribsd/lib/l
ibc/mips -DNLS  -DSOFTFLOAT -D__DBINTERFACE_PRIVATE -I/home/rnw24/git/cheribsd/l
ib/libc/../../contrib/gdtoa -I/home/rnw24/git/cheribsd/lib/libc/../../contrib/li
bc-vis -DINET6 -I/home/rnw24/obj/mips.mips64/home/rnw24/git/cheribsd/lib/libc -I
/home/rnw24/git/cheribsd/lib/libc/resolv -D_ACL_PRIVATE -DPOSIX_MISTAKE -I/home/
rnw24/git/cheribsd/lib/libc/../libmd -I/home/rnw24/git/cheribsd/lib/libc/../../c
ontrib/jemalloc/include -DMALLOC_PRODUCTION -I/home/rnw24/git/cheribsd/lib/libc/
../../contrib/tzcode/stdtime -I/home/rnw24/git/cheribsd/lib/libc/stdtime  -I/hom
e/rnw24/git/cheribsd/lib/libc/locale -DBROKEN_DES -DPORTMAP -DDES_BUILTIN -I/hom
e/rnw24/git/cheribsd/lib/libc/rpc -I/home/rnw24/git/cheribsd/lib/libc/mips/softf
loat  -I/home/rnw24/git/cheribsd/lib/libc/softfloat -DSOFTFLOAT_FOR_GCC -DYP -DN
S_CACHING -DSYMBOL_VERSIONING -std=gnu99 -Wsystem-headers -Werror -Wall -Wno-for
mat-y2k -Wno-uninitialized -Wno-pointer-sign   -I/home/rnw24/git/cheribsd/lib/li
butil -I/home/rnw24/git/cheribsd/lib/msun/mips -I/home/rnw24/git/cheribsd/lib/ms
un/src -c /home/rnw24/git/cheribsd/lib/libc/mips/string/memcpy.c -o memcpy.o
In file included from /home/rnw24/git/cheribsd/lib/libc/mips/string/memcpy.c:31:
/home/rnw24/obj/mips.mips64/home/rnw24/git/cheribsd/tmp/usr/include/machine/cher
i.h:75:31: error: 
      field may not be qualified with an address space
        __capability cheri_codeptr_t    co_codecap;
                                        ^
/home/rnw24/obj/mips.mips64/home/rnw24/git/cheribsd/tmp/usr/include/machine/cher
i.h:76:31: error: 
      field may not be qualified with an address space
        __capability cheri_dataptr_t    co_datacap;
```

Similarly, the compiler appears not to permit __capability decoration of automatic variables where typedefs are used: ```__capability void *c``` is allowed as a local variable, but ```__capability cheri_dataptr_t c``` is not allowed.

The FreeBSD source code doesn't make extensive use of typedefs for pointer types -- which is probably why we haven't encountered this a lot yet -- but a lot of other code does. It would be great if we could annotate any pointer with ```__capability``` without having to worry about whether it used a typedef or not.

**Comment by davidchisnall** [comment]
This is going to be very complicated to fix.  The issue is that we're slightly abusing the address space qualifier to make other `typedef` usage easier.  Really, the qualifier should be applied to the pointer, so we'd write:

```
void __capability *foo;
```
and not
```
__capability void *foo;
```

This correct use of the qualifier would break the kind of thing that we do in `tcpdump`, where we define something like:
```
typedef __capability somestruct capthingy;
```
And then, when the address of an object of this type it taken, it is a capability type.

Because we do the qualification this way around, and slightly inconsistently, when you use `typedef`s as in the example, you're trying to define a `struct` that has two fields in different address spaces (rather than a struct with fields that are pointers to different address spaces).  This is obviously nonsense, as `struct`s are contiguous.

I'm not sure what the best solution is.

**Comment by rwatson** [comment]
Yes, I rather feared something along these lines, only with less technical detail. :-) However, at least in the medium term, it's something we will need to fix. In the short term, it means we may encounter greater compatibility problems as we work with software that uses typedefs more extensively than the FreeBSD base system.
