### ISSUE TITLE
function pointers passed to varidac functions are 8 bytes in pure capability mode

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/clang#71]
I've added a test to demonstrate that when passed to varidac functions, function pointers are still treated as integer register values.

CTSRD-CHERI/cheri-c-tests@5a48b952d03953adeb5eb2ecb5a2ab1e91efbf88 

This is breaking libedit consumers.

I've tested this with a freshly built SDK.

**Comment by davidchisnall** [comment]
Seems to work if you pass `foo` and not `&foo`.

**Comment by davidchisnall** [comment]
It looks as if `&foo` gives a simple unary cast expression, bypassing the normal function-to-pointer decay logic.
