### ISSUE TITLE
pointer_interpretation integer not making pointers into integers in structs

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/clang#73]
This code:

```C
unknow_Pragma("pointer_interpretation push")
_Pragma("pointer_interpretation integer")
struct foo {
        int foo;
        void *bar;
};

struct bar {
        int foo;
        long bar;
};
_Pragma("pointer_interpretation pop")

_Static_assert(sizeof(struct foo) == 16, "foo is incorrectly sized");
_Static_assert(sizeof(struct bar) == 16, "bar is incorrectly sized");
_Static_assert(sizeof(struct foo) == sizeof(struct bar),
    "structs not equal");
```

Fails as follows:
```
clang -target cheri-unknown-freebsd -mabi=sandbox -c foo.c
foo.c:14:1: error: static_assert failed "foo is incorrectly sized"
_Static_assert(sizeof(struct foo) == 16, "foo is incorrectly sized");
^              ~~~~~~~~~~~~~~~~~~~~~~~~
foo.c:16:1: error: static_assert failed "structs not equal"
_Static_assert(sizeof(struct foo) == sizeof(struct bar),
^              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
```

I would expect the void * to be converted into a 64-bit integer.

**Comment by davidchisnall** [comment]
It looks as if they are the correct types in the generated IR, however `sizeof` is returning the wrong values.

**Comment by davidchisnall** [comment]
Actually, it is working, but in a slightly odd way: the alignment of the field is being treated as 32, not 8, so you're ending up with a struct that has a load of extra padding.  The field itself is of the correct type.

**Comment by brooksdavis** [comment]
I was really hoping that I'd the the same sizeof() so I could make `struct ifreq` not contain capabilities as a temporary workaround in `ioctl`. The fact that the sizes aren't the same means I need to add adapters for ~150 commands.

**Comment by brooksdavis** [comment]
On a side note, it would be really handy if we had a tool to audit struct layout compatibility.

**Comment by davidchisnall** [comment]
The fix for this is very simple: I had some code in the type layout that say 'if this is a pointer in AS0, treat it as being a pointer in the default address space'.  I believe that this is no longer required as we're now constructing pointers in the correct address space.  Hopefully the test suite will catch issues if it isn't...
