### ISSUE TITLE
Casts from pointer to integer should use the offset in the pure-capability ABI

### ISSUE THREAD

**Issue by davidchisnall** [CTSRD-CHERI/clang#74]
`CFromPtr` / `CToPtr` (generated from `inttoptr` / `ptrtoint` casts) are intended for use in the hybrid ABI and are not particularly meaningful in the pure capability world.  We don't expect to be able to round-trip pointers through integers, so we should use the offset.  

Currently, we have some inconsistency:
```
void *x = /* something */;
__intcap_t c = (__intcap_t)x; // x and c contain the same value
int ci = (int)c; // ci contains the offset of c (also the offset of x)
int pi = (int)x; // pi contains the result of CToPtr x, which is probably null
```
For consistency, we should probably use the same logic for pointer to integer casts that we currently use for `__[u]intcap_t` to integer casts.

This should address CTSRD-CHERI/cheribsd#52

**Comment by rwatson** [comment]
One might argue that this calls for a new instruction, CFromInt, which doesn't require a contextual starting capability, and simply returns the moral equivalent of a NULL-derived CSetOffset. Right now, CFromPtr is our original of NULL pointers in CHERI, but it could be that CFromIntr($zero) would be preferable to avoid making (unnecessary, inappropriate?) use of other capability registers.
