### ISSUE TITLE
annotation to clear (argument) registers before calling marked functions

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/clang#75]
I'd like to be able to annotate system call declarations so that the compiler would clear unused argument registers before invoking the syscall so failure to follow the prototype for pseudo varargs syscalls won't result in passing an unexpected capability.  e.g. calling `fcntl()` as `fcntl(fd, F_GETLK)` (missing `struct flock *` argument) should reliably pass an cleared capability.

**Comment by davidchisnall** [comment]
Should this just clear capability arguments?  Do you need some mechanism for differentiating passing a null value explicitly and not passing anything?

**Comment by brooksdavis** [comment]
Clearing capability arguments is most critical, but clearing all might be better and would be more general.

In general I don't think I need to differentiate `fcntl(fd, F_GETLK, NULL)` from `fcntl(fd, F_GETLK)` since both are bugs.  What I want to avoid is `fcntl(fd, F_GETLK)` becoming `fcntl(fd, F_GETLK, <some-random-capability>)`.

Writing this answer, I'm now wondering if this actually makes sense for CheriABI because in CheriABI `fcntl(fd, F_GETLK)` will result in a length violation when calling `va_arg()` on a zero length array.  It does seem like good hygiene to not pass unnecessary junk to the kernel, but the problem I was thinking of when I wrote this request doesn't actually exist.  A different one would exist if someone declared `int fcntl(int, int, long);` for a userspace program, but this wouldn't fix it.

**Comment by davidchisnall** [comment]
You can also explicitly check the length of the `va_list` to find the size of the variadic frame.

**Comment by davidchisnall** [comment]
Closing unless more thinking indicates that this actually would be useful.
