### ISSUE TITLE
__CHERI_SANDBOX__ should probably now be __CHERI_PURE__ or __CHERI_ALL_POINTERS_ARE_CAPS__

### ISSUE THREAD

**Issue by rwatson** [CTSRD-CHERI/clang#81]
The Clang-defined ```__CHERI_SANDBOX__``` to indicate pure-capability code generation should probably now be ```__CHEIR_PURE__``` or some other variation on the theme (e.g., ```__CHERI_ALL_POINTERS_ARE_CAPS__```), as the pure-capability ABI and model is no longer used only with sandboxing. We should retain the old define for now for compatibility purposes. (This might also imply replacing use of the term 'sandbox' in other places in Clang/LLVM...).

**Comment by brooksdavis** [comment]
We should also probably eliminate most directly uses of `__CHERI_SANDBOX__` or it's successor from CheriBSD in favor a CheriABI specific define (likely set based on `__CHERI_SANDBOX__`) to avoid conflation of "compiling in pure capability mode" and "targeting mips64-cheriabi".

**Comment by davidchisnall** [comment]
Fixed in 6cbccea
