### ISSUE TITLE
__sync_ builtins should work on capabilities.

### ISSUE THREAD

**Issue by davidchisnall** [CTSRD-CHERI/clang#83]
```
error: address argument to atomic builtin must be a pointer to 1,2,4,8 or 16 byte type ('__attribute__((address_space(200))) intptr_t *' (aka '__attribute__((address_space(200))) __intcap_t *') invalid)
                        __sync_add_and_fetch(refCount, 1);
                        ^                    ~~~~~~~~
```

CHERI doesn't advertise the `__sync*` builtins as working with capabilities.  Bumping the size to that of a capability register will probably work for the front end, but there may need to be some related back-end changes.

**Comment by davidchisnall** [comment]
This will be easier to tackle once the in-progress upstream rationalisation of LLVM atomics has happened and the lowering to function calls is performed closer to the back end.

**Comment by arichardson** [comment]
Current state is that they work but are really inefficient due to using atomic libcalls.
