### ISSUE TITLE
capsizefix: excessive output

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/clang#85]
`capsizefix` emits two lines for every function in a program like
```
Unable to find size of symbol at 012015fd5f for pointer at 0x12015fc20
Using section size (130831 bytes) instead
```
These provide no value when `capsizefix` is working and are obscuring other diagnostic output in the linking process.  For example, building `ssh` for CheriABI is triggering non-fatal linker assertions, but they are lost after thousands of lines of `capsizefix` diagnostics are emitted.

**Comment by davidchisnall** [comment]
I've reduced the output, please reopen if it's still too chatty for you.
