### ISSUE TITLE
feature request: __attribute((pointer_interpretation_capability))

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/clang#9]
It would be helpful to have an attribute to use in definitions like:
```C
#define CHERI_TCPDUMP_CCALL \
    __attribute__((cheri_ccall)) \
    __attribute__((cheri_method_suffix("_cap"))) \
    __attribute__((cheri_method_class(cheri_tcpdump)))
```
So I could make all the pointers used by a given function into capabilities.  Alternatively, __attribute__((cheri_ccall)) and __attribute__((cheri_ccallee)) could just imply that.

**Comment by brooksdavis** [comment]
A pragma the only applies to the next declaration would also work as I could use _Pragma

**Comment by davidchisnall** [comment]
This is actually quite a complex request.  It's fairly easy to make all of the pointer arguments into capabilities, but what about indirect pointers (e.g. pointer to struct containing pointer)?  Requiring that those be capabilities is a lot harder.  Ideally, we'd have a static analyser plugin that would detect this kind of use.

**Comment by brooksdavis** [comment]
Making the arguments and return value into capabilities would resolve all the cases I've run into so far.
