### ISSUE TITLE
Unexpected pointer case behavior

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/clang#92]
The following code:

```C
#include <sys/types.h>

extern void *func(void *);

void *
func(void *ptr)
{
        
        return ((void*)(size_t)ptr);
}
```

Produces when compiled with `cheri-unknown-freebsd-clang -O0 -mabi=sandbox -c foo.c`:
```
0000000000000000 <func>:
   0:   67bdffa0        daddiu  sp,sp,-96
   4:   ebcbeac3        csd     s8,sp,88(c11)
   8:   03a0f025        move    s8,sp
   c:   67c10020        daddiu  at,s8,32
  10:   49a15841        csetoffset      c1,c11,at
  14:   64010020        daddiu  at,zero,32
  18:   48210840        csetbounds      c1,c1,at
  1c:   64010000        daddiu  at,zero,0
  20:   f8610000        csc     c3,zero,0(c1)
  24:   d8210000        clc     c1,zero,0(c1)
  28:   49a20802        cgetoffset      v0,c1
  2c:   48810007        cfromptr        c1,c0,zero
  30:   49a30881        csetoffset      c3,c1,v0
  34:   e82bf0c3        csd     at,s8,24(c11)
  38:   03c0e825        move    sp,s8
  3c:   cbcbeac3        cld     s8,sp,88(c11)
  40:   67bd0060        daddiu  sp,sp,96
  44:   49008800        cjr     c17
  48:   00000000        nop
```

I was expecting the `(size_t)` cast to produce to produce the virtual address with `ctoptr` and the `(void *)` cast to turn it back into a pointer via a `cfromptr` not for the offset to be extracted and added to a `NULL` pointer.

**Comment by davidchisnall** [comment]
If this is in the pure-capability ABI, then this behaviour is expected.  Casts from provenance-free integer types to pointer types will never materialise valid pointers in this model.

**Comment by brooksdavis** [comment]
Reflecting on this more, I realize we need the `NULL` plus an increment behavior some of the time.  For example
```C
#define MAP_FAILED      ((void *)-1)
```
but much of the time we want cfromptr.  For example:
```C
tls_init = (void*) phdr[i].p_vaddr;
```
The question is, what should the default be and how should we express the alternative?  I might argue that the `MAP_FAILED` case would make more sense as:
```C
#define MAP_FAILED      ((void *)(intptr_t)-1)
```
For the other case, we might want the ability to specify a capability other than `$c0` to be the default one (perhaps via a pragma) with one option being, don't allow integer to pointer conversions.

**Comment by brooksdavis** [comment]
If that's going to be the model then we need a warning about such attempts for all but small constant values.

**Comment by brooksdavis** [comment]
Is the `(size_t)` behavior expected?  I though it was supposed to produce the virtual address.

**Comment by davidchisnall** [comment]
Cast to `size_t` should give virtual address.  I'm a bit surprised that it doesn't, as I thought that duktape depended on that working correctly.  I'll take a look.

If we're going to add a warning, then we also need some qualifier on the type, so that we can do something like `(__invalid void*)(size_t)foo` and silence the warning, otherwise all of the (very many) things that are really trying to store a non-integer value in a pointer will fail.  We can probably model this in the same way as the Objective-C ARC bridging casts, so I'll take a look at implementing it.

**Comment by davidchisnall** [comment]
Actually, we probably don't need the explicit attribute, as `(void*)(uintptr_t)(size_t)foo` should do the same thing.

**Comment by davidchisnall** [comment]
The warning was added in d45b8dd
